[package]
name = "moonlighter"
version = "0.6.0"
edition = "2024"
authors = ["Voker57 voker57@gmail.com"]
license = "AGPLv3"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
tracing = { git="https://github.com/mladedav/tracing.git", branch="dm/filter" }
serde = { version = "1.0.228", features = ["derive"] }
anyhow = "1.0.102"
tracing-subscriber =  {git="https://github.com/mladedav/tracing.git", features = ["env-filter", "fmt"], branch="dm/filter" }
